resources:
  - name: myJenkinsTrigger
    type: OutgoingWebhook
    configuration:
      webhookName: jenkinswebhook 
      parameters: token=PIPELINES1
  - name: myBuildInfo
    type: BuildInfo
    configuration:
      buildName: sample_build
      buildNumber: 1
      externalCI: rr_jenkins
pipelines:
  - name: jenkins_trigger
    steps:
      - name: step_1
        type: Bash
        configuration:
          outputResources:
            - name: myJenkinsTrigger
        execution:
          onExecute:
            - echo 'Triggered Jenkins job'
       
            
  - name: pipelines_trigger
    steps:
      - name: step_2
        type: Bash
        configuration:
          inputResources:
            - name: myBuildInfo
        execution:
          onExecute:
            - echo 'Jenkins job triggered Pipelines'   
